language: python
jobs:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=black
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=mypy
install: pip install tox
script: tox
